'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Contact

    '''<summary>
    '''Contact_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contact_ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Label_Recipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Recipient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Recipient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Recipient As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label_Member_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Member_Code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Member_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Member_Code As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label_Person_To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Person_To As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Person_To_Salutation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Person_To_Salutation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Person_To_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Person_To_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_Position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Position As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Position As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_EMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_EMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Company As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Company As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_Address_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Address_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Address_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_Address_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Address_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Address_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label_Address_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label_Address_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Address_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Btn_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Reset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GV_New_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GV_New_Contact As Global.System.Web.UI.WebControls.GridView
End Class
